main_app/models/ingredient.py
# pylint: disable=maybe-no-member

from main_app import db
from .associations import ing_att_assc, ing_rec_assc
from .food_group import Food_Group
from flask import Markup

class Ingredient(db.Model):
    __tablename__ = 'ingredients'
    ing_id = db.Column(db.Integer, primary_key=True)
    ing_name = db.Column(db.String(12), unique=True, nullable=False)
    ing_fg_id = db.Column(db.Integer, db.ForeignKey('food_groups.fg_id'), nullable=False)
    ing_desc = db.Column(db.String(255), unique=False, nullable=True)
    ing_pic = db.Column(db.String(255), unique=False, nullable=True)
    food_group = db.relationship('Food_Group')

    attributes = db.relationship('Attribute', secondary=ing_att_assc)
    recipes = db.relationship('Recipe', secondary=ing_rec_assc)

    def __repr__(self):
        return '<Ingredient %r>' % self.ing_name

    def num_pos_attributes(self):
        """
        Returns the number of postitive attributes belonging to the ingredient
        """
        count = 0
        for attr in self.attributes:
            if attr.att_pos_neg:
                count+=1
        return count

    def num_neg_attributes(self):
        """
        Returns the number of negative attributes belonging to the ingredient
        """
        count = 0
        for attr in self.attributes:
            if not attr.att_pos_neg:
                count+=1
        return count

    def rendered_image(self):
        """
        Wraps the image in HTML to be rendered in the table view later
        """
        html = '<img src="'+self.ing_pic+ '"width="160" height="160" alt="'+self.ing_name+ '" title="'+self.ing_name+ '" >'
        return Markup(html)

main_app/models/recipe.py
from main_app import db
from .associations import ing_rec_assc

class Recipe(db.Model):
    __tablename__ = 'recipes'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(16), unique=True, nullable=False)
    default = db.Column(db.Boolean) # initialize this to 1 if you're adding a default meal to the database, custom meals will be 0
    
    ingredients = db.relationship('Ingredient', secondary=ing_rec_assc)

    def cumulative_neg_attributes(self):
        """
        Total number of negative attributes across all ingredients
        """
        count = 0
        for ing in self.ingredients:
            for att in ing.attributes:
                if not att:
                    count += 1
        return count

    def cumulative_pos_attributes(self):
        """
        Total number of negative attributes across all ingredients
        """
        count = 0
        for ing in self.ingredients:
            for att in ing.attributes:
                if att:
                    count += 1
        return count

main_app/routes/account_bp.py
from .__init__ import *

account_bp = Blueprint('account_bp', __name__)

# [CREATE FORMS] -----------------------------------------------------------------
class LoginForm(FlaskForm):
    username = StringField('Username', validators=[InputRequired()])
    password = PasswordField('Password', validators=[InputRequired()])
    remember = BooleanField('Remember me')

class SignUpForm(FlaskForm):
    username = StringField('Username', validators=[InputRequired(), Length(min=3, max=16)])
    password = PasswordField('Password', validators=[InputRequired(), Length(min=8, max=32)])
# --------------------------------------------------------------------------------

# [DESIGNATE ROUTES] -------------------------------------------------------------
@login_manager.user_loader
def load_user(account_id):
    return Account.query.get(int(account_id))

@account_bp.route('/')
@login_required
def load_page():
    return render_template('index_view.html', username=current_user.username)

@account_bp.route('/login', methods=['GET', 'POST'])
def login():
    # If the user is already logged in, redirect back to app
    if current_user.is_authenticated:
        return redirect(url_for('account_bp.load_page'))

    form = LoginForm()

    if form.validate_on_submit():
        # Query database for username to see if it exists
        account = Account.query.filter_by(username=form.username.data).first()
        if account:
            # If the username exists, check if the password is correct, if so login, otherwise redirect back to same page
            # Need to add message to user if not correct.
            if check_password_hash(account.password, form.password.data):
                login_user(account, remember=form.remember.data)
                return redirect(url_for('account_bp.load_page'))
        #If username or password is invalid, flash and redirect
        flash('Invalid username or password provided')
        return redirect(url_for('account_bp.login'))

    return render_template('login_view.html', form=form)

@account_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('account_bp.login'))

@account_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    # If the user is already logged in, redirect back to app
    if current_user.is_authenticated:
        return redirect(url_for('account_bp.load_page'))

    form = SignUpForm()

    if form.validate_on_submit():
        # Query database, if account already exists with that username. Redirect back to sign up.
        account = Account.query.filter_by(username=form.username.data).first()
        if account:
            flash('That username is taken')
            return redirect(url_for('account_bp.signup'))

        # The username isn't taken. Hash the password, create an Account object, put it in db.
        hashed_password = generate_password_hash(form.password.data, method='sha256')
        new_account = Account(username=form.username.data, password=hashed_password)
        db.session.add(new_account)
        db.session.commit()

        # Log the new user in, then redirect to success
        login_user(new_account)
        return redirect(url_for('account_bp.load_page'))

    return render_template('signup_view.html', form=form)
# --------------------------------------------------------------------------------

main_app/templates/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

main_app/templates/base.html
<html>
    <head>
        {% block head %}
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href={{ url_for('static', filename='style.css') }}/>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
        {% endblock %}
    </head>
    <body>

<nav class="navbar navbar-expand-lg navbar-light bg-light hide_navbar" style="margin-bottom:15px">

  <a class="navbar-brand" href="/">Ethical Eating</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto hide_navbar">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="Search">Search</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/create">Create Recipe</a>
      </li>
    </ul>
    <span class="navbar-text hide_navbar">
        <span>{{username}}</span>
        <a href="{{ url_for('account_bp.logout') }}">Log Out</a>
    </span>
  </div>
</nav>
        {% block body %}
        {% endblock %}
    </body>
</html>

main_app/templates/create_recipe_view.html
{% extends "base.html" %}
{% block title %}Recipe Builder{% endblock %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href={{ url_for('static', filename='style.css') }}/>
{% endblock %}
{% block body %}

<div class="bodyDiv">
<h3 style="margin-left:4%;font-size:18">To get started, select ingredients from the table below. After it has been added, you can check the ingredient's possible substitutions by clicking on the "Alt" button.</h3>
<hr class="majorLine">

<div class="container-fluid" id="creationAccordion">
    <div class="row">
        <div class="col-md-4">
            <div class="accordion creationAccordion2" id="accordionExample">
                
                <div class="card">  <!-- Fruit -->
                    <div class="card-header" id="headingOne">
                    <h2 class="mb-0">
                        <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Fruit
                        </button>
                    </h2>
                    </div>

                    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                    <div class="card-body createTable">
                        {{fruit_table}}
                    </div>
                    </div>
                </div>  <!-- Fruit -->
                
                <div class="card">  <!-- Grain -->
                    <div class="card-header" id="headingTwo">
                    <h2 class="mb-0">
                        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        Grain
                        </button>
                    </h2>
                    </div>
                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                    <div class="card-body createTable">
                        {{grain_table}}
                    </div>
                    </div>
                </div>  <!-- Grain -->
                
                <div class="card">  <!-- Vegetable -->
                    <div class="card-header" id="headingThree">
                    <h2 class="mb-0">
                        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                        Vegetable
                        </button>
                    </h2>
                    </div>
                    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                    <div class="card-body createTable">
                        {{vegetable_table}}
                    </div>
                    </div>
                </div>  <!-- Vegetable -->
                
                <div class="card">  <!-- Protein -->
                    <div class="card-header" id="headingFour">
                    <h2 class="mb-0">
                        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                        Protein
                        </button>
                    </h2>
                    </div>
                    <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordionExample">
                    <div class="card-body createTable">
                        {{protein_table}}
                    </div>
                    </div>
                </div>  <!-- Protein -->
                
                <div class="card">  <!-- Dairy -->
                    <div class="card-header" id="headingFive">
                    <h2 class="mb-0">
                        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                        Dairy
                        </button>
                    </h2>
                    </div>
                    <div id="collapseFive" class="collapse" aria-labelledby="headingFive" data-parent="#accordionExample">
                    <div class="card-body createTable">
                        {{dairy_table}}
                    </div>
                    </div>
                </div>  <!-- Dairy -->
                
            </div>
        </div>
        <!-- Middle Column -->
        <div class="col-md-4">
            <input type="text" name="recipe_name" id="recipe_name_textbox" placeholder="Name your recipe">
            <table class="createTable addedIng">
                <thead>
                    <tr id="recipe_head_row" style="display: none;">
                        <th>Ingredient Name</th>
                        <th>Food Group</th>
                        <th>Number of Positive Attributes</th>
                        <th>Number of Negative Attributes</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="recipe_table_body"></tbody>
            </table>
            <button class="modifySaveButton" id="save_recipe_button">Save Recipe</button>
            <div class="alert alert-primary" role="alert" style="display:none"></div>
        </div>
        <!-- Right column -->
        <div class="col-md-4">
            <div class="addedIng" id="right_div">
                
            </div>
        </div>
    </div>
</div>
</div>

<script>
    let ingredient_count = ["{{ ing_count[0] }}", "{{ ing_count[1] }}", "{{ ing_count[2] }}", "{{ ing_count[3] }}", "{{ ing_count[4] }}"];
</script>
<script src="{{ url_for('static', filename='js/create_recipe.js') }}"></script>
{% endblock %}

main_app/templates/index_view.html
{% extends "base.html" %}       
{% block title %}Success{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block body %}
<div class="bodyDiv">
<center style="margin-top:15%">
<h1>Welcome {{username}}!</h1>
<h3>Use the navigation bar at the top of the screen to get started.</h3>
</center>
</div>
{% endblock %}

main_app/templates/ingredient_view.html
{% extends "base.html" %}      
{% block title %}Ingredient Detail - {{ingredient.ing_name}}{% endblock %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href={{ url_for('static', filename='style.css') }}/>
{% endblock %}
{% block body %}


<div class="bodyDiv">
<!-- INGREDIENT NAME BEGINS HERE -->
<h1 style="margin-left:5%">
    <b>{{ingredient.ing_name}}</b>
</h1>
<center><hr class="majorLine"></center>


<!-- INGREDIENT INFORMATION BEGINS HERE -->
<div>
    <p style="float: left; border: 3px solid gray;margin-left:15%;margin-bottom:10px">
    <img src={{ ingredient.ing_pic }} width="290" height="290" alt=ingredient.ing_name title=ingredient.ing_name>
    <h2 style="margin-left:40%">
        <b>Summary</b>
    </h2>
</div>
<hr class="minorLine" style="float:right;margin-right:13%;margin-left:0px">
<div class="infoArea">
    <h3>
        Food Group: {{ingredient.food_group.fg_name}}
    </h3>
    <h3>
        Description: {{ingredient.ing_desc}} 
    </h3>
</div>
<br>



<hr class="minorLine" style="float:right;margin-right:13%;margin-left:0px">
<center><hr class="majorLine"></center>



<!-- ETHICAL ATTRIBUTES BEGIN HERE -->
<div class="attributeBubble" style="clear:both;float:left;margin-left:10%;margin-top:8px">
    <h2 style="text-align:center">
        <b>Positive Attributes</b>
    </h2>
    <p style="text-align:center"> - <u>A list of ethically positive facts about this ingredient</u></p>
    <ul style="text-align:left">
        {% for attr in ingredient.attributes %}
            {% if attr.att_pos_neg %}
                <li>{{ attr.att_desc }}</li>
            {% endif %}
        {% endfor %}
    </ul>
</div>
<div class="attributeBubble" style="float:right;margin-right:10%;margin-top:8px">
    <h2 style="text-align:center">
        <b>Negative Attributes</b>
    </h2>
    <p style="text-align:center"> - <u>A list of not-so-ethical facts about this ingredient</u></p>
    <ul style="text-align:left">
        {% for attr in ingredient.attributes %}
            {% if not attr.att_pos_neg %}
                <li>{{ attr.att_desc }}</li>
            {% endif %}
        {% endfor %}
    </ul>
</div>

<div class="shortSpace"></div>


<div class="greyBlock">
    <h3 style="margin-top:10px"><u>Possible Alternatives</u></h3>
    <p>Here are some ingredients that could be used as a substitute:</p>
    <ol style="margin-bottom:20px;margin-left:0px;list-style-position:inside;text-align:center">
        {% for ings in ingredient.food_group.ingredients %}
            <li>{{ ings.ing_name }}</li>
        {% endfor %}
    </ol>
</div>
</div>
{% endblock %}

main_app/templates/login_view.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Login{% endblock %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href={{ url_for('static', filename='hide_navbar.css') }}/>
{% endblock %}
{% block body %}
<div class="container">
  

  <center>
  <h1 style="margin-top:10%;font-size:100px">Ethical Eating</h1>

  <form class="form-signin loginForm" method="POST" action ="/login">
    <h2 class="form-signin-heading">Log In</h2>
    {{ form.hidden_tag() }}
    {{ wtf.form_field(form.username) }}
    {{ wtf.form_field(form.password) }}
    {{ wtf.form_field(form.remember) }}
    <button class="btn btn-lg btn-primary btn-block" type="submit" style="width:270px">Sign In</button>
  </form>

  <!-- flash -->
  <center>
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        {% for msg in messages %}
          <p>{{msg}}</p>
        {% endfor %}
      {% endif %}
    {% endwith %}
  </center>
    <!-- flash -->

  <form action="/signup" style="width:30%">
    <button class="btn btn-lg btn-secondary btn-block" type="submit">Create Account</button>
  </form>
  </center>
  
</div> <!-- /container -->
{% endblock %}

main_app/templates/recipe_view.html
{% extends "base.html" %}
{% block title %}Recipe Detail - {{recipe.name}} {% endblock %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href={{ url_for('static', filename='style.css') }}/>
{% endblock %}
{% block body %}
<div class="bodyDiv">
<h1>Recipe: {{recipe.name}}</h1>
<h3 style="margin-left:8%">Cumulative negative attributes: {{recipe.cumulative_neg_attributes()}}</h3>
<h3 style="margin-left:8%;margin-bottom:20px">Cumulative positive attributes: {{recipe.cumulative_pos_attributes()}}</h3>

<hr class="majorLine">

<h1>Ingredients:</h1>
<div class="searchTable" style="margin-top:20px">
    {{ table }}
</div>
</div>
{% endblock %}

main_app/templates/search_view.html
{% extends "base.html" %}       
{% block title %}Search Page{% endblock %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href={{ url_for('static', filename='style.css') }}/>
{% endblock %}
{% block body %}

<!-- PAGE NAME BEGINS HERE -->
<h1 style="margin-left:5%">
  <b>Search</b>
</h1>
<center><hr class="majorLine"></center>

<!-- FORM BEGINS HERE -->
<center>
{% from "_formhelpers.html" import render_field %}
<form class="searchForm" method=post>
  <dl>
    {{ render_field(form.select) }}
    {{ render_field(form.search) }}
  </dl>
  <p><input type=submit value=Go>
</form>

<!-- TABLE BEGINS HERE -->
<div class="searchTable" style="clear:both">
{% if table %}
<h2><u>Results:</u></h2 style="margin-top:30px">
{{ table }}
{% endif %}
</center>
{% endblock %}

main_app/templates/signup_view.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Sign Me Up{% endblock %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href={{ url_for('static', filename='hide_navbar.css') }}/>
{% endblock %}
{% block body %}
<div class="container">
  <!-- flash -->
  {% with messages = get_flashed_messages() %}
    {% if messages %}
      {% for msg in messages %}
        <p>{{msg}}</p>
      {% endfor %}
    {% endif %}
  {% endwith %}
  <!-- flash -->

  <center>
  <form class="form-signin loginForm" method="POST" action="/signup">
    <h2 class="form-signin-heading">Create An Account</h2>
    {{ form.hidden_tag() }}
    {{ wtf.form_field(form.username) }}
    <div><p>- Username length must be between 3 and 16 inclusive</p></div>
    {{ wtf.form_field(form.password) }}
    <div><p>- Password length must be between 8 and 32 inclusive</p></div>
    <button class="btn btn-lg btn-primary btn-block" type="submit" style="width:270px">Sign Up</button>
  </form>

  <form action="/login" style="width:30%">
    <button class="btn btn-lg btn-secondary btn-block" type="submit">Login</button>
  </form>
  </center>
  
</div> <!-- /container -->
{% endblock %}

main_app/templates/test_name.html
{% extends "base.html" %}       
{% block title %}Template_Test{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block body %}
<h1>Hello, {{name}}!</h1>
{% endblock %}